/*
 * Sign-Up Form — automated tests (Jasmine)
 * ------------------------------------------------------------------
 * These 10 specs run INSIDE index.html (the Jasmine Spec Runner) and
 * check the structure and accessibility of your sign-up <form>. You
 * only edit the <body> of index.html — leave the <head> and doctype
 * exactly as they are.
 *
 * DO NOT EDIT THIS FILE. Make every spec below turn green by building
 * an accessible sign-up form.
 *
 * Note: Jasmine draws its own results panel in the page, so we ignore
 * anything inside its reporter and only look at YOUR content.
 */

describe("Sign-Up Form — structure & accessibility", function () {

  // Elements matching `sel` inside <body>, excluding Jasmine's own UI.
  function q(sel) {
    return Array.prototype.slice.call(document.querySelectorAll("body " + sel))
      .filter(function (el) {
        return !el.closest(".jasmine_html-reporter") && !el.closest('[class*="jasmine"]');
      });
  }

  // Is this input associated with a <label>? Either the input is wrapped
  // inside a <label>, or it has an id with a matching <label for="id">.
  function isLabelled(input) {
    if (input.closest("label")) return true;
    var id = input.getAttribute("id");
    return !!(id && q('label[for="' + id + '"]').length > 0);
  }

  it("1. the page has exactly one <form>", function () {
    expect(q("form").length).toBe(1);
  });

  it("2. there is a name field: <input type=\"text\">", function () {
    expect(q('input[type="text"]').length).toBeGreaterThanOrEqual(1);
  });

  it("3. there is an email field: <input type=\"email\">", function () {
    expect(q('input[type="email"]').length).toBe(1);
  });

  it("4. the email field is required", function () {
    var email = q('input[type="email"]')[0] || null;
    expect(email).not.toBeNull();
    expect(!!(email && email.hasAttribute("required"))).toBe(true);
  });

  it("5. there is a password field: <input type=\"password\">", function () {
    expect(q('input[type="password"]').length).toBe(1);
  });

  it("6. the password field is required", function () {
    var pw = q('input[type="password"]')[0] || null;
    expect(pw).not.toBeNull();
    expect(!!(pw && pw.hasAttribute("required"))).toBe(true);
  });

  it("7. the password field has minlength=\"8\"", function () {
    var pw = q('input[type="password"]')[0] || null;
    expect(pw).not.toBeNull();
    expect(pw && pw.getAttribute("minlength")).toBe("8");
  });

  it("8. there is a terms checkbox: <input type=\"checkbox\">", function () {
    expect(q('input[type="checkbox"]').length).toBeGreaterThanOrEqual(1);
  });

  it("9. there is a submit control (<button type=\"submit\"> or <input type=\"submit\">)", function () {
    expect(q('button[type="submit"], input[type="submit"]').length).toBeGreaterThanOrEqual(1);
  });

  it("10. every text/email/password/checkbox input has an associated <label>", function () {
    var inputs = q('input[type="text"], input[type="email"], input[type="password"], input[type="checkbox"]');
    expect(inputs.length).toBeGreaterThanOrEqual(4);
    var unlabelled = inputs.filter(function (el) { return !isLabelled(el); });
    expect(unlabelled.length).toBe(0);
  });
});
