/*
 * Specificity Fix-It — automated tests (Jasmine)
 * ------------------------------------------------------------------
 * These 10 specs run INSIDE index.html (the Jasmine Spec Runner) and
 * read the CSS RULES you write in main.css. They simulate the CSS
 * cascade (importance -> specificity -> source order) to decide which
 * colour actually wins on the "Buy now" link.
 *
 * You only edit main.css. Leave the page markup and this file exactly
 * as they are. DO NOT EDIT THIS FILE.
 * ------------------------------------------------------------------
 */

describe("Specificity Fix-It — resolve the conflict without !important", function () {

  // ---- read author rules (skip Jasmine's own stylesheet) --------
  function allRules() {
    var out = [], sheets = document.styleSheets || [];
    for (var i = 0; i < sheets.length; i++) {
      if (/jasmine/i.test(sheets[i].href || "")) continue;
      var rules;
      try { rules = sheets[i].cssRules || sheets[i].rules; } catch (e) { continue; }
      if (!rules) continue;
      for (var j = 0; j < rules.length; j++) {
        if (rules[j].selectorText && rules[j].style) out.push(rules[j]);
      }
    }
    return out;
  }

  // Specificity of a selector as [ids, classes, elements].
  function spec(sel) {
    sel = String(sel);
    var a = (sel.match(/#[\w-]+/g) || []).length;
    var b = (sel.match(/\.[\w-]+/g) || []).length
          + (sel.match(/\[[^\]]*\]/g) || []).length
          + (sel.match(/:(?!:)[\w-]+/g) || []).length;
    var c = (sel.match(/(^|[\s>+~])[a-zA-Z][\w-]*/g) || []).length
          + (sel.match(/::[\w-]+/g) || []).length;
    return [a, b, c];
  }
  function cmpSpec(x, y) {           // >0 if x wins
    for (var i = 0; i < 3; i++) if (x[i] !== y[i]) return x[i] - y[i];
    return 0;
  }

  // Query the target at TEST time (the <body> isn't parsed yet when this
  // describe() first runs from the <head>, so don't cache it up here).
  function getTarget() { return document.querySelector("#buy"); }
  function norm(v) { return String(v).toLowerCase().replace(/\s+/g, ""); }
  function hasCta(sel) { return /\.cta(\b|[^\w-])/.test(sel); }

  // Every author rule that sets `color` and matches the target link.
  function colorRulesForTarget() {
    var target = getTarget(), rules = allRules(), out = [];
    if (!target) return out;
    for (var i = 0; i < rules.length; i++) {
      var r = rules[i];
      var val = r.style.getPropertyValue("color");
      if (!val) continue;
      var m = false;
      try { m = target.matches(r.selectorText); } catch (e) { m = false; }
      if (!m) continue;
      out.push({
        selector: r.selectorText,
        value: val,
        important: r.style.getPropertyPriority("color") === "important",
        spec: spec(r.selectorText),
        order: i
      });
    }
    return out;
  }

  // The cascade winner: !important first, then specificity, then order.
  function winner() {
    var list = colorRulesForTarget(), best = null;
    for (var i = 0; i < list.length; i++) {
      var r = list[i];
      if (!best) { best = r; continue; }
      if (r.important !== best.important) { if (r.important) best = r; continue; }
      var c = cmpSpec(r.spec, best.spec);
      if (c > 0) best = r;
      else if (c === 0 && r.order > best.order) best = r;
    }
    return best;
  }

  // The rule carrying the intended brand colour (selector contains .cta).
  function ctaColorRule() {
    var rules = allRules();
    for (var i = 0; i < rules.length; i++) {
      if (hasCta(rules[i].selectorText) && rules[i].style.getPropertyValue("color")) return rules[i];
    }
    return null;
  }

  // The original grey rule "#content a" (contains #content, no .cta).
  function greyColorRule() {
    var rules = allRules();
    for (var i = 0; i < rules.length; i++) {
      var s = rules[i].selectorText;
      if (norm(s).indexOf("#contenta") !== -1 && !hasCta(s) &&
          rules[i].style.getPropertyValue("color")) return rules[i];
    }
    return null;
  }

  function anyImportant() {
    var rules = allRules();
    for (var i = 0; i < rules.length; i++) {
      var st = rules[i].style;
      for (var j = 0; j < st.length; j++) {
        if (st.getPropertyPriority(st[j]) === "important") return true;
      }
    }
    return false;
  }

  var GREY = "rgb(107,114,128)";     // #6b7280 — the colour that should NOT win

  // ---- tests ----------------------------------------------------

  // Test 1 — no !important anywhere in main.css.
  it("uses no !important anywhere in the stylesheet", function () {
    expect(anyImportant()).toBe(false);
  });

  // Test 2 — the grey rule specifically no longer forces color with !important.
  it("removes !important from the grey #content a rule", function () {
    var g = greyColorRule();
    expect(g).not.toBeNull();
    expect(g.style.getPropertyPriority("color")).toBe("");
  });

  // Test 3 — the Buy now link's winning colour equals the intended brand colour.
  it("makes the intended brand colour win on the Buy now link", function () {
    var w = winner(), cta = ctaColorRule();
    expect(cta).not.toBeNull();
    expect(w).not.toBeNull();
    expect(norm(w.value)).toBe(norm(cta.style.getPropertyValue("color")));
  });

  // Test 4 — the link no longer renders the grey colour.
  it("no longer lets the grey colour win", function () {
    var w = winner();
    expect(w).not.toBeNull();
    expect(norm(w.value)).not.toBe(norm(GREY));
  });

  // Test 5 — the intended rule is no longer a lone class (id or element added).
  it("raises the intended rule's specificity beyond a lone class", function () {
    var cta = ctaColorRule();
    expect(cta).not.toBeNull();
    var s = spec(cta.selectorText);          // [ids, classes, elements]
    expect(s[0] + s[2]).toBeGreaterThan(0);
  });

  // Test 6 — the intended rule out-specifies the grey rule.
  it("makes the intended selector more specific than #content a", function () {
    var cta = ctaColorRule(), g = greyColorRule();
    expect(cta).not.toBeNull();
    expect(g).not.toBeNull();
    expect(cmpSpec(spec(cta.selectorText), spec(g.selectorText))).toBeGreaterThan(0);
  });

  // Test 7 — the winning colour rule keeps the .cta class.
  it("wins with a selector that includes the .cta class", function () {
    var w = winner();
    expect(w).not.toBeNull();
    expect(hasCta(w.selector)).toBe(true);
  });

  // Test 8 — the winning selector is a refinement: it names BOTH #content and .cta.
  it("refines the intended rule using both #content and .cta", function () {
    var w = winner();
    expect(w).not.toBeNull();
    var refined = norm(w.selector).indexOf("#content") !== -1 && hasCta(w.selector);
    expect(refined).toBe(true);
  });

  // Test 9 — existing selectors are refined, not deleted: #content a survives AND intended wins.
  it("keeps the existing #content a rule while the intended colour wins", function () {
    var g = greyColorRule(), w = winner(), cta = ctaColorRule();
    var intendedWins = !!(w && cta && norm(w.value) === norm(cta.style.getPropertyValue("color")));
    expect(!!g && intendedWins).toBe(true);
  });

  // Test 10 — the intended colour wins by specificity, not by importance.
  it("wins by specificity, not by !important on the winning rule", function () {
    var w = winner();
    expect(w).not.toBeNull();
    expect(w.important).toBe(false);
  });

});
