/*
 * Class Timetable — automated tests (Jasmine)
 * ------------------------------------------------------------------
 * These 10 specs run INSIDE index.html (the Jasmine Spec Runner) and
 * check the structure and accessibility of your data table. You only
 * edit the <body> of index.html — leave the <head> and doctype exactly
 * as they are.
 *
 * DO NOT EDIT THIS FILE. Make every spec below turn green by building
 * an accessible timetable.
 *
 * Note: Jasmine draws its own results panel in the page, so we ignore
 * anything inside its reporter and only look at YOUR content.
 */

describe("Class Timetable — structure & accessibility", function () {

  // Elements matching `sel` inside <body>, excluding Jasmine's own UI.
  function q(sel) {
    return Array.prototype.slice.call(document.querySelectorAll("body " + sel))
      .filter(function (el) {
        return !el.closest(".jasmine_html-reporter") && !el.closest('[class*="jasmine"]');
      });
  }

  it("1. the page has exactly one <table>", function () {
    expect(q("table").length).toBe(1);
  });

  it("2. the table has a non-empty <caption>", function () {
    var cap = q("table caption")[0] || null;
    expect(cap).not.toBeNull();
    expect(!!(cap && cap.textContent.trim().length > 0)).toBe(true);
  });

  it("3. the table has a <thead>", function () {
    expect(q("table thead").length).toBe(1);
  });

  it("4. the table has a <tbody>", function () {
    expect(q("table tbody").length).toBe(1);
  });

  it("5. the header row uses column headers: <th scope=\"col\">", function () {
    expect(q('thead th[scope="col"]').length).toBeGreaterThanOrEqual(1);
  });

  it("6. every <th> has a scope of \"col\" or \"row\"", function () {
    var ths = q("th");
    expect(ths.length).toBeGreaterThanOrEqual(1);
    var bad = ths.filter(function (th) {
      var s = th.getAttribute("scope");
      return s !== "col" && s !== "row";
    });
    expect(bad.length).toBe(0);
  });

  it("7. body rows use row headers: <th scope=\"row\">", function () {
    expect(q('tbody th[scope="row"]').length).toBeGreaterThanOrEqual(1);
  });

  it("8. the <tbody> has at least 3 rows", function () {
    expect(q("tbody tr").length).toBeGreaterThanOrEqual(3);
  });

  it("9. every body row has the same number of cells as the header row", function () {
    var headRow = q("thead tr")[0] || null;
    expect(headRow).not.toBeNull();
    var cols = headRow ? headRow.querySelectorAll("th, td").length : 0;
    expect(cols).toBeGreaterThan(0);
    var rows = q("tbody tr");
    var mismatched = rows.filter(function (r) {
      return r.querySelectorAll("th, td").length !== cols;
    });
    expect(mismatched.length).toBe(0);
  });

  it("10. data lives in <td> cells inside the <tbody>", function () {
    expect(q("tbody td").length).toBeGreaterThanOrEqual(1);
  });
});
