/* =====================================================================
   Make It Responsive — automated checks (10)
   These specs read YOUR CSS from main.css (via document.styleSheets) and
   verify a mobile-first responsive grid:
     base (mobile) = 1 column, tablet = 2 columns, desktop = 3 columns,
     built with min-width media queries, plus non-overflowing images.
   You do not edit this file. Fix everything in main.css.
   ===================================================================== */

/* ---- helpers ---------------------------------------------------------- */
function allSheets() {
  return Array.prototype.slice.call(document.styleSheets);
}

// Flatten every style rule to { sel, style, mw } where mw is the min-width
// pixel value of the enclosing @media block (or null for base rules).
function flatRules() {
  var out = [];
  allSheets().forEach(function (ss) {
    var rules;
    try { rules = ss.cssRules || ss.rules; } catch (e) { rules = null; }
    if (!rules) return;
    Array.prototype.forEach.call(rules, function (r) {
      if (r.selectorText && r.style) {
        out.push({ sel: r.selectorText, style: r.style, mw: null });
      } else if (r.cssRules && r.media) {
        var m = /min-width:\s*(\d+)/.exec(r.media.mediaText || '');
        var mw = m ? parseInt(m[1], 10) : null;
        Array.prototype.forEach.call(r.cssRules, function (ir) {
          if (ir.selectorText && ir.style) {
            out.push({ sel: ir.selectorText, style: ir.style, mw: mw });
          }
        });
      }
    });
  });
  return out;
}

// Does a selectorText target this exact selector (allowing comma lists)?
function targets(sel, target) {
  return sel.split(',').some(function (p) { return p.trim() === target; });
}

// Last-wins declared value of a property for `target` at a given media level.
function decl(target, prop, wantMw) {
  var val = '';
  flatRules().forEach(function (r) {
    if (r.mw === wantMw && targets(r.sel, target)) {
      var v = r.style.getPropertyValue(prop);
      if (v) val = v;
    }
  });
  return val.trim();
}

// Value of a property for any selector that mentions `img`.
function imgDecl(prop) {
  var val = '';
  flatRules().forEach(function (r) {
    if (r.mw === null && /\bimg\b/.test(r.sel)) {
      var v = r.style.getPropertyValue(prop);
      if (v) val = v;
    }
  });
  return val.trim();
}

// Count grid tracks, expanding repeat(n, X).
function countTracks(v) {
  if (!v) return 0;
  v = v.trim().replace(/repeat\(\s*(\d+)\s*,\s*([^)]*)\)/g, function (_, n, inner) {
    var one = inner.trim();
    return new Array(parseInt(n, 10) + 1).join(one + ' ');
  });
  return v.split(/\s+/).filter(Boolean).length;
}

// Distinct min-width breakpoints that set .gallery columns, ascending.
function galleryBreakpoints() {
  var map = {};
  flatRules().forEach(function (r) {
    if (r.mw !== null && targets(r.sel, '.gallery')) {
      var gtc = r.style.getPropertyValue('grid-template-columns');
      if (gtc) map[r.mw] = countTracks(gtc);
    }
  });
  return Object.keys(map)
    .map(function (k) { return { mw: parseInt(k, 10), cols: map[k] }; })
    .sort(function (a, b) { return a.mw - b.mw; });
}

function hasGap(mw) {
  return !!(decl('.gallery', 'gap', mw) || decl('.gallery', 'grid-gap', mw) ||
            decl('.gallery', 'row-gap', mw) || decl('.gallery', 'column-gap', mw));
}

/* ---- specs ------------------------------------------------------------ */
describe('Make It Responsive', function () {

  it('1. .gallery uses display: grid (base styles)', function () {
    expect(decl('.gallery', 'display', null)).toBe('grid');
  });

  it('2. base (mobile) layout is a single column', function () {
    expect(countTracks(decl('.gallery', 'grid-template-columns', null))).toBe(1);
  });

  it('3. .gallery has a gap between cards', function () {
    expect(hasGap(null)).toBe(true);
  });

  it('4. at least one min-width media query targets .gallery', function () {
    expect(galleryBreakpoints().length >= 1).toBe(true);
  });

  it('5. a breakpoint switches .gallery to 2 columns', function () {
    expect(galleryBreakpoints().some(function (b) { return b.cols === 2; })).toBe(true);
  });

  it('6. a second min-width media query targets .gallery', function () {
    expect(galleryBreakpoints().length >= 2).toBe(true);
  });

  it('7. a breakpoint switches .gallery to 3 columns', function () {
    expect(galleryBreakpoints().some(function (b) { return b.cols === 3; })).toBe(true);
  });

  it('8. breakpoints are mobile-first (2-col width < 3-col width)', function () {
    var bps = galleryBreakpoints();
    var two = bps.filter(function (b) { return b.cols === 2; })[0];
    var three = bps.filter(function (b) { return b.cols === 3; })[0];
    var ok = !!two && !!three && two.mw < three.mw;
    expect(ok).toBe(true);
  });

  it('9. images use max-width: 100% so they never overflow', function () {
    expect(imgDecl('max-width').replace(/\s+/g, '')).toBe('100%');
  });

  it('10. images use height: auto to keep their proportions', function () {
    expect(imgDecl('height')).toBe('auto');
  });

});
