/*
 * My First Page — automated tests (Jasmine)
 * ------------------------------------------------------------------
 * These 10 specs run INSIDE index.html (the Jasmine Spec Runner) and
 * check the content you add to the <body>. You only edit the <body>
 * of index.html — leave the <head> and the doctype exactly as they are.
 *
 * DO NOT EDIT THIS FILE. Make every spec below turn green by writing
 * headings, paragraphs and a line break in the <body>.
 *
 * Note: Jasmine draws its own results panel in the page, so we ignore
 * anything inside its reporter and only look at YOUR content.
 */

describe("My First Page — page content", function () {

  // Elements matching `sel` inside <body>, excluding Jasmine's own UI.
  function q(sel) {
    return Array.prototype.slice.call(document.querySelectorAll("body " + sel))
      .filter(function (el) {
        return !el.closest(".jasmine_html-reporter") && !el.closest('[class*="jasmine"]');
      });
  }
  function text(el) { return (el.textContent || "").trim(); }

  it("1. the page has exactly one <h1> heading", function () {
    expect(q("h1").length).toBe(1);
  });

  it("2. the <h1> has non-empty text", function () {
    var h1 = q("h1")[0] || null;
    expect(h1).not.toBeNull();
    expect(h1 && text(h1).length).toBeGreaterThan(0);
  });

  it("3. the page has at least two <h2> section headings", function () {
    expect(q("h2").length).toBeGreaterThanOrEqual(2);
  });

  it("4. every <h2> heading has non-empty text", function () {
    var h2 = q("h2");
    expect(h2.length).toBeGreaterThan(0);
    expect(h2.every(function (h) { return text(h).length > 0; })).toBe(true);
  });

  it("5. the page has at least two <p> paragraphs", function () {
    expect(q("p").length).toBeGreaterThanOrEqual(2);
  });

  it("6. every <p> paragraph has non-empty text", function () {
    var ps = q("p");
    expect(ps.length).toBeGreaterThanOrEqual(2);
    expect(ps.every(function (p) { return text(p).length > 0; })).toBe(true);
  });

  it("7. the page uses at least one <br> line break", function () {
    expect(q("br").length).toBeGreaterThanOrEqual(1);
  });

  it("8. the <h1> appears before the first <h2> (heading hierarchy)", function () {
    var h1 = q("h1")[0] || null;
    var h2 = q("h2")[0] || null;
    expect(h1).not.toBeNull();
    expect(h2).not.toBeNull();
    var following = h1 && h2 &&
      (h1.compareDocumentPosition(h2) & Node.DOCUMENT_POSITION_FOLLOWING);
    expect(!!following).toBe(true);
  });

  it("9. every <h2> section is followed by at least one <p>", function () {
    var h2 = q("h2");
    expect(h2.length).toBeGreaterThan(0);
    var ok = h2.every(function (h) {
      var n = h.nextElementSibling;
      while (n) {
        if (n.tagName === "P") return true;
        if (n.tagName === "H1" || n.tagName === "H2") return false; // next section reached first
        n = n.nextElementSibling;
      }
      return false;
    });
    expect(ok).toBe(true);
  });

  it("10. the body is a complete page (at least five content elements: one h1, two h2, two p)", function () {
    var total = q("h1").length + q("h2").length + q("p").length;
    expect(total).toBeGreaterThanOrEqual(5);
  });
});
